### ISSUE TITLE
关于金场数据

### ISSUE THREAD

**Issue by SAPikachu** [kamicloud/mahjong-science-server#1]
想确认一下现在你那边有在做金场的数据服务器么？我最近开始考虑弄一台便宜点的服务器处理金场，不过如果你那边已经做得差不多的话我就先不搞了~

**Comment by kamicloud** [comment]
> 想确认一下现在你那边有在做金场的数据服务器么？我最近开始考虑弄一台便宜点的服务器处理金场，不过如果你那边已经做得差不多的话我就先不搞了~

暂时还没有数据分析，只开启了一个爬牌谱的程序，存储的是雀魂所有段位场观战数据。
目前mongo存了4g的数据，99888张谱。您方便加IM吗，微信或者QQ沟通更方便一些。

**Comment by SAPikachu** [comment]
好，我的 QQ 是 2824481 ，你的 QQ 是邮件地址里面那个吗？可能需要我加你。

**Comment by kamicloud** [comment]
你加一下我吧，刚下班，还在回家路上😂

**Comment by SAPikachu** [comment]
已加~
